Add missing scenario for ci-docker-node-legacy job
Has been failing for a while with the following error:

```
  File "./test-infra/jenkins/bootstrap.py", line 906, in job_script
ValueError: ('cannot find scenario for job', 'ci-docker-node-legacy')
```

Change-Id: I090dec0724b75fb72582de050f5f3c78775dc3d7